CREATE DATABASE IF NOT EXISTS `myangyarecord` DEFAULT CHARSET UTF8MB4;

create table if not exists `recordgroup`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `uid` INT UNSIGNED,
    `name` VARCHAR(100) NOT NULL,
    `desc` VARCHAR(300) NOT NULL,
    `mapid` VARCHAR(32) NOT NULL,
    `score` INT NOT NULL DEFAULT -1,
    `is_deleted` BOOLEAN DEFAULT FALSE,
    `is_public` BOOLEAN DEFAULT FALSE,
    `show_lived_level` BOOLEAN DEFAULT TRUE,
    `create_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`uid`) REFERENCES `user`(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS `record`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `group_id` INT UNSIGNED,
    `admin_id` VARCHAR(32),
    `level` TINYINT UNSIGNED,
    `data` VARCHAR(256),
    `is_deleted` BOOLEAN DEFAULT FALSE,
    `create_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`group_id`) REFERENCES `recordgroup`(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

create table IF NOT EXISTS `user`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `pw` VARCHAR(100) NOT NULL,
    `is_deleted` BOOLEAN DEFAULT FALSE,
    `is_banned` BOOLEAN DEFAULT FALSE,
    `auth` INT DEFAULT 0,
    `create_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_date` DATETIME DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP,
    `last_login` DATETIME DEFAULT NULL,
    `email` VARCHAR(100) NOT NULL UNIQUE,
    `verified` BOOLEAN DEFAULT FALSE.
    `hitokoto` VARCHAR(300) DEFAULT NULL,
    `avatar_url` VARCHAR(100) DEFAULT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

