CREATE DATABASE IF NOT EXISTS `myangyarecord` DEFAULT CHARSET UTF8MB4;

create table if not exists `recordgroup`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `desc` VARCHAR(300) NOT NULL,
    `uid` INT,
    `mapid` VARCHAR(32) NOT NULL,
    `is_deleted` BOOLEAN DEFAULT FALSE,
    `create_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS `record`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `admin_id` VARCHAR(32),
    FOREIGN KEY (`group_id`) REFERENCES `recordgroup`(`id`),
    `level` TINYINT UNSIGNED,
    `is_deleted` BOOLEAN DEFAULT FALSE,
    `create_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

create table IF NOT EXISTS `user`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `pw` VARCHAR(100) NOT NULL,
    `is_deleted` BOOLEAN DEFAULT FALSE,
    `is_banned` BOOLEAN DEFAULT FALSE,
    `auth` INT DEFAULT 0,
    `create_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_date` DATETIME DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP,
    `last_login` DATETIME DEFAULT NULL,
    `email` VARCHAR(100) NOT NULL UNIQUE,
    `verified` BOOLEAN DEFAULT FALSE
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

