import json
import os

with open('./src/geojson/japan/todofukenFiles.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    todofuken_list = data['todofukenFiles']

ts_code = "// This file is generated by geojsonReaderGen.py\nexport const allPrefJsons = [\n"
for pref in todofuken_list:
    jp_name, file_name, en_name = pref
    file_name_without_ext = os.path.splitext(file_name)[0]
    ts_code += f' ["{jp_name}", "{en_name}", require("../../geojson/japan/todofuken/{file_name}")],\n'

ts_code += f'];\n'
with open('./src/pages/Japan/geojsonReader.ts', 'w', encoding='utf-8') as f:
    f.write(ts_code)
